apiVersion: v1
data:
  config.yaml: "attributes:\n  kubernetes:\n    enable: true\n    cluster_name: ekscluster01-ipvs\n\
    discovery:\n  instrument:\n  - k8s_namespace: '*'\n  exclude_instrument:\n  -\
    \ k8s_namespace: telemetry-system\n  - k8s_namespace: central-observability\n\
    \  - k8s_namespace: amazon-guardduty\nroutes:\n  unmatched: heuristic\notel_traces_export:\n\
    \  endpoint: http://telemetry-cluster.telemetry-system.svc:4318\n  protocol: http/protobuf\n"
kind: ConfigMap
metadata:
  annotations: {}
  name: telemetry-beyla
  namespace: telemetry-system
---
apiVersion: v1
data:
  config.yaml: "extensions:\n  health_check:\n    endpoint: 0.0.0.0:13133\n  file_storage:\n\
    \    directory: /var/lib/otelcol/storage\n    create_directory: true\nprocessors:\n\
    \  memory_limiter:\n    check_interval: 1s\n    limit_mib: 380\n    spike_limit_mib:\
    \ 80\n  resource/cluster:\n    attributes:\n    - key: k8s.cluster.name\n    \
    \  value: ekscluster01-ipvs\n      action: upsert\n    - key: cluster\n      value:\
    \ ekscluster01-ipvs\n      action: upsert\n    - key: cloud.account.id\n     \
    \ value: 061525506239\n      action: upsert\n    - key: cloud.region\n      value:\
    \ ap-northeast-2\n      action: upsert\n  batch:\n    timeout: 5s\n    send_batch_size:\
    \ 1024\n    send_batch_max_size: 2048\nexporters:\n  otlp/central:\n    endpoint:\
    \ vpce-0ad17229cc37f9137-oqfpq1s7.vpce-svc-0ac371f4606926e0f.ap-northeast-2.vpce.amazonaws.com:4317\n\
    \    tls:\n      ca_file: /tls/ca.crt\n      cert_file: /tls/tls.crt\n      key_file:\
    \ /tls/tls.key\n      server_name_override: telemetry.platform.internal\n    sending_queue:\n\
    \      enabled: true\n      queue_size: 1000\n      num_consumers: 2\n      storage:\
    \ file_storage\n    retry_on_failure:\n      enabled: true\n      max_elapsed_time:\
    \ 0s\nservice:\n  extensions:\n  - health_check\n  - file_storage\n  pipelines:\n\
    \    metrics:\n      receivers:\n      - k8s_cluster\n      - prometheus\n   \
    \   - otlp\n      processors:\n      - memory_limiter\n      - resource/cluster\n\
    \      - batch\n      exporters:\n      - otlp/central\n    traces:\n      receivers:\n\
    \      - otlp\n      processors:\n      - memory_limiter\n      - resource/cluster\n\
    \      - batch\n      exporters:\n      - otlp/central\nreceivers:\n  otlp:\n\
    \    protocols:\n      grpc:\n        endpoint: 0.0.0.0:4317\n      http:\n  \
    \      endpoint: 0.0.0.0:4318\n  k8s_cluster:\n    auth_type: serviceAccount\n\
    \    collection_interval: 60s\n    node_conditions_to_report:\n    - Ready\n \
    \   - MemoryPressure\n    - DiskPressure\n    - PIDPressure\n    allocatable_types_to_report:\n\
    \    - cpu\n    - memory\n    - pods\n  prometheus:\n    config:\n      scrape_configs:\n\
    \      - job_name: annotated-pods\n        scrape_interval: 60s\n        kubernetes_sd_configs:\n\
    \        - role: pod\n        relabel_configs:\n        - source_labels:\n   \
    \       - __meta_kubernetes_pod_annotation_prometheus_io_scrape\n          action:\
    \ keep\n          regex: 'true'\n        - source_labels:\n          - __meta_kubernetes_namespace\n\
    \          action: drop\n          regex: telemetry-system\n        - source_labels:\n\
    \          - __meta_kubernetes_pod_phase\n          action: keep\n          regex:\
    \ Running\n        - source_labels:\n          - __meta_kubernetes_pod_annotation_prometheus_io_path\n\
    \          action: replace\n          target_label: __metrics_path__\n       \
    \   regex: (.+)\n        - source_labels:\n          - __address__\n         \
    \ - __meta_kubernetes_pod_annotation_prometheus_io_port\n          action: replace\n\
    \          regex: ([^:]+)(?::\\d+)?;(\\d+)\n          replacement: $$1:$$2\n \
    \         target_label: __address__\n        - source_labels:\n          - __meta_kubernetes_namespace\n\
    \          target_label: namespace\n        - source_labels:\n          - __meta_kubernetes_pod_name\n\
    \          target_label: pod\n"
kind: ConfigMap
metadata:
  annotations: {}
  name: telemetry-cluster
  namespace: telemetry-system
---
apiVersion: v1
data:
  config.yaml: "extensions:\n  health_check:\n    endpoint: 0.0.0.0:13133\n  file_storage:\n\
    \    directory: /var/lib/otelcol/storage\n    create_directory: true\nprocessors:\n\
    \  memory_limiter:\n    check_interval: 1s\n    limit_mib: 380\n    spike_limit_mib:\
    \ 80\n  resource/cluster:\n    attributes:\n    - key: k8s.cluster.name\n    \
    \  value: ekscluster01-ipvs\n      action: upsert\n    - key: cluster\n      value:\
    \ ekscluster01-ipvs\n      action: upsert\n    - key: cloud.account.id\n     \
    \ value: 061525506239\n      action: upsert\n    - key: cloud.region\n      value:\
    \ ap-northeast-2\n      action: upsert\n  batch:\n    timeout: 5s\n    send_batch_size:\
    \ 1024\n    send_batch_max_size: 2048\nexporters:\n  otlp/central:\n    endpoint:\
    \ vpce-0ad17229cc37f9137-oqfpq1s7.vpce-svc-0ac371f4606926e0f.ap-northeast-2.vpce.amazonaws.com:4317\n\
    \    tls:\n      ca_file: /tls/ca.crt\n      cert_file: /tls/tls.crt\n      key_file:\
    \ /tls/tls.key\n      server_name_override: telemetry.platform.internal\n    sending_queue:\n\
    \      enabled: true\n      queue_size: 1000\n      num_consumers: 2\n      storage:\
    \ file_storage\n    retry_on_failure:\n      enabled: true\n      max_elapsed_time:\
    \ 0s\nservice:\n  extensions:\n  - health_check\n  - file_storage\n  pipelines:\n\
    \    metrics:\n      receivers:\n      - kubeletstats\n      processors:\n   \
    \   - memory_limiter\n      - resource/cluster\n      - batch\n      exporters:\n\
    \      - otlp/central\n    logs:\n      receivers:\n      - filelog\n      processors:\n\
    \      - memory_limiter\n      - resource/cluster\n      - batch\n      exporters:\n\
    \      - otlp/central\nreceivers:\n  filelog:\n    include:\n    - /var/log/pods/*/*/*.log\n\
    \    exclude:\n    - /var/log/pods/telemetry-system_*/*/*.log\n    start_at: end\n\
    \    include_file_path: true\n    include_file_name: false\n    storage: file_storage\n\
    \    max_log_size: 256KiB\n    retry_on_failure:\n      enabled: true\n      max_elapsed_time:\
    \ 0s\n    operators:\n    - type: container\n      id: container-parser\n  kubeletstats:\n\
    \    collection_interval: 60s\n    auth_type: serviceAccount\n    endpoint: https://${env:K8S_NODE_IP}:10250\n\
    \    metric_groups:\n    - node\n    - pod\n    - container\n    - volume\n"
kind: ConfigMap
metadata:
  annotations: {}
  name: telemetry-node
  namespace: telemetry-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  name: telemetry-cluster
  namespace: telemetry-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: telemetry-cluster
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: 1d6bb24165768f4d721ca3638228cdf8dc6cda6dad2214f5c02d084f035acadc
      labels:
        app: telemetry-cluster
    spec:
      containers:
      - args:
        - --config=/conf/config.yaml
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: K8S_NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: otel/opentelemetry-collector-contrib:0.161.0
        imagePullPolicy: IfNotPresent
        name: collector
        ports:
        - containerPort: 13133
          name: health
          protocol: TCP
        - containerPort: 4317
          name: otlp-grpc
          protocol: TCP
        - containerPort: 4318
          name: otlp-http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 13133
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /
            port: 13133
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: config
          readOnly: true
        - mountPath: /tls
          name: tls
          readOnly: true
        - mountPath: /var/lib/otelcol
          name: state
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccount: central-telemetry
      serviceAccountName: central-telemetry
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: telemetry-cluster
        name: config
      - name: tls
        secret:
          defaultMode: 420
          secretName: telemetry-client-tls
      - hostPath:
          path: /var/lib/central-telemetry/telemetry-cluster
          type: DirectoryOrCreate
        name: state
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: '2'
  name: telemetry-beyla
  namespace: telemetry-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: telemetry-beyla
  template:
    metadata:
      annotations:
        checksum/config: 23133a5658882c877771aa7502c340139d6cf469fc2fb60a9c98a44888c967d5
      labels:
        app: telemetry-beyla
    spec:
      containers:
      - env:
        - name: BEYLA_CONFIG_PATH
          value: /conf/config.yaml
        - name: BEYLA_LOG_LEVEL
          value: WARN
        - name: OTEL_METRICS_EXPORTER
          value: none
        image: grafana/beyla:3.35.0
        imagePullPolicy: IfNotPresent
        name: beyla
        resources:
          limits:
            memory: 1536Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          privileged: true
          readOnlyRootFilesystem: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: config
          readOnly: true
        - mountPath: /var/run/beyla
          name: run
        - mountPath: /sys/fs/cgroup
          name: cgroup
          readOnly: true
        - mountPath: /sys/kernel/tracing
          name: tracefs
      dnsPolicy: ClusterFirst
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: central-telemetry
      serviceAccountName: central-telemetry
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: telemetry-beyla
        name: config
      - emptyDir: {}
        name: run
      - hostPath:
          path: /sys/fs/cgroup
          type: ''
        name: cgroup
      - hostPath:
          path: /sys/kernel/tracing
          type: ''
        name: tracefs
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: '1'
  name: telemetry-node
  namespace: telemetry-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: telemetry-node
  template:
    metadata:
      annotations:
        checksum/config: d880a2478d4e2657827b715bcd5d26a165e0d241feffeb07d18fa37f45ad1b41
      labels:
        app: telemetry-node
    spec:
      containers:
      - args:
        - --config=/conf/config.yaml
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: K8S_NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: otel/opentelemetry-collector-contrib:0.161.0
        imagePullPolicy: IfNotPresent
        name: collector
        ports:
        - containerPort: 13133
          name: health
          protocol: TCP
        - containerPort: 4317
          name: otlp-grpc
          protocol: TCP
        - containerPort: 4318
          name: otlp-http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 13133
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /
            port: 13133
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: config
          readOnly: true
        - mountPath: /tls
          name: tls
          readOnly: true
        - mountPath: /var/lib/otelcol
          name: state
        - mountPath: /var/log/pods
          name: logs
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccount: central-telemetry
      serviceAccountName: central-telemetry
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: telemetry-node
        name: config
      - name: tls
        secret:
          defaultMode: 420
          secretName: telemetry-client-tls
      - hostPath:
          path: /var/lib/central-telemetry/telemetry-node
          type: DirectoryOrCreate
        name: state
      - hostPath:
          path: /var/log/pods
          type: Directory
        name: logs
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: telemetry-cluster
  namespace: telemetry-system
spec:
  clusterIP: 172.20.215.83
  clusterIPs:
  - 172.20.215.83
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app: telemetry-cluster
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  name: central-telemetry
  namespace: telemetry-system
