-- since: 2.2.0
-- Security Group Rules & Usage — rule inventory + Athena-based traffic evidence
-- (docs/superpowers/specs/2026-08-13-security-group-rules-usage-design.md, Approved 2026-08-19;
-- flag `sg_rule_activity_enabled`, default false — ADR-019 §2 register row).
--
-- sg_rule_inventory is a mutable current-state cache (one row per rule_id) used by the Rules page.
-- sg_rule_inventory_versions is append-only and is the actual matching source of truth — the
-- inventory cache alone cannot answer "what did this rule look like when this flow was observed."
-- See the design spec's "Why versioning" section for why matching is day-granular, not per-flow.

CREATE TABLE sg_flow_sources (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id       text NOT NULL,
  region           text NOT NULL,
  workgroup        text NOT NULL,
  database_name    text NOT NULL,
  table_name       text NOT NULL,
  enabled          boolean NOT NULL DEFAULT true,
  validation       jsonb NOT NULL DEFAULT '{}',
  created_by_sub   text NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (account_id, region)
);

CREATE TABLE sg_rule_inventory (
  account_id       text NOT NULL,
  region           text NOT NULL,
  rule_id          text NOT NULL,
  group_id         text NOT NULL,
  is_egress        boolean NOT NULL,
  protocol         text NOT NULL,
  from_port        integer,
  to_port          integer,
  peer_kind        text NOT NULL,
  peer_value       text NOT NULL,
  description      text,
  fingerprint      text NOT NULL,
  first_seen_at    timestamptz NOT NULL,
  last_seen_at     timestamptz NOT NULL,
  active           boolean NOT NULL DEFAULT true,
  PRIMARY KEY (account_id, region, rule_id)
);

-- Append-only; matching source of truth. valid_from/valid_to are *observation* timestamps (when the
-- daily snapshot first/last saw this fingerprint), not rule-change timestamps — see the design spec.
CREATE TABLE sg_rule_inventory_versions (
  account_id       text NOT NULL,
  region           text NOT NULL,
  rule_id          text NOT NULL,
  fingerprint      text NOT NULL,
  group_id         text NOT NULL,
  is_egress        boolean NOT NULL,
  protocol         text NOT NULL,
  from_port        integer,
  to_port          integer,
  peer_kind        text NOT NULL,
  peer_value       text NOT NULL,
  valid_from       timestamptz NOT NULL,
  valid_to         timestamptz,  -- NULL = currently open
  PRIMARY KEY (account_id, region, rule_id, valid_from)
);

CREATE INDEX sg_rule_inventory_versions_lookup_idx
  ON sg_rule_inventory_versions (account_id, region, rule_id, valid_from, valid_to);

CREATE TABLE sg_eni_membership_snapshots (
  account_id       text NOT NULL,
  region           text NOT NULL,
  vpc_id           text NOT NULL,  -- required: reverse peer-IP lookups must scope by VPC first
  observed_at      timestamptz NOT NULL,
  eni_id           text NOT NULL,
  group_ids        jsonb NOT NULL,
  private_ips      jsonb NOT NULL,
  PRIMARY KEY (account_id, region, observed_at, eni_id)
);

CREATE INDEX sg_eni_membership_snapshots_vpc_idx
  ON sg_eni_membership_snapshots (account_id, region, vpc_id, observed_at);

-- Primary key is scoped to (account_id, region, rule_id, observed_on); rule_fingerprint is a plain
-- column, not part of the key — see design spec for why keying on fingerprint would double-count.
CREATE TABLE sg_rule_activity_daily (
  account_id              text NOT NULL,
  region                  text NOT NULL,
  rule_id                 text NOT NULL,
  rule_fingerprint        text NOT NULL,
  observed_on             date NOT NULL,
  compatible_match_count  bigint NOT NULL DEFAULT 0,
  compatible_bytes        bigint NOT NULL DEFAULT 0,
  overlap_match_count     bigint NOT NULL DEFAULT 0,
  unique_eni_count        integer NOT NULL DEFAULT 0,
  last_observed_at        timestamptz,
  coverage                jsonb NOT NULL DEFAULT '{}',
  PRIMARY KEY (account_id, region, rule_id, observed_on)
);

-- Intentionally no uniqueness constraint on (flow_source_id, partition_start, partition_end) — every
-- scan attempt inserts a new row; current status = the row with the latest started_at for that
-- partition. See design spec's Data model section.
CREATE TABLE sg_rule_scan_runs (
  id                    text PRIMARY KEY,
  flow_source_id        bigint NOT NULL REFERENCES sg_flow_sources(id),
  status                text NOT NULL DEFAULT 'queued'
                          CHECK (status IN ('queued','running','succeeded','failed')),
  partition_start       timestamptz,
  partition_end         timestamptz,
  athena_query_id       text,
  data_scanned_bytes    bigint,
  rows_processed        bigint,
  coverage              jsonb NOT NULL DEFAULT '{}',
  error_code            text,
  started_at            timestamptz NOT NULL DEFAULT now(),
  finished_at           timestamptz
);

CREATE INDEX sg_rule_scan_runs_partition_idx
  ON sg_rule_scan_runs (flow_source_id, partition_start, partition_end, started_at DESC);
